contentColumnType: text
fieldGroup: 3fd20431-b1f5-4026-8f6d-2e75d24d8332
handle: locationZipCode
instructions: ''
name: 'Location Zip Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
